### ISSUE TITLE
Strange loop in ChannelAccess.cc

### ISSUE THREAD

**Issue by devilkuro** [sommer/veins#30]
The line 100 of ChannelAccess.cc
https://github.com/sommer/veins/blob/master/src/veins/base/connectionManager/ChannelAccess.cc#L100
            int radioStart = i->second->getId();
            int radioEnd = radioStart + i->second->size();
            for (int g = radioStart; g != --radioEnd; ++g)
                sendDirect(static_cast<cPacket*>(msg->dup()),delay, msg->getDuration(), i->second->getOwnerModule(), g);

In loop 
for (int g = radioStart; g != --radioEnd; ++g)
, it will be ignored if i->second->size()==1, or it will be an endless loop if i->second->size()==2 or other even number.
In the code above, 'i' is an const_iterator of std::map<const NicEntry*, cGate*, NicEntryComparator> "outConns" which contains the cGate* "radioIn" of each out-connected nics.
So, the 'i->second->size()' stands for the size of "radioIn" which is always 1 here.

I think the correct code may be
for (int g = radioStart; g != radioEnd - 1; ++g)
.

Send the msg copies to the connected nics and send the original to the last nic.

**Comment by sommer** [comment]
You sound unsure. Have you tried?

**Comment by namnatulco** [comment]
I think they might be right about this, for some reason there is a very odd iteration in this entire block (which, if I understand the comments correctly, isn't veins-related at all).

```
        // use Andras stuff
        if( i != gateList.end() ){
        	simtime_t delay = SIMTIME_ZERO;
            for(; i != --gateList.end(); ++i){
            	//calculate delay (Propagation) to this receiving nic
            	delay = calculatePropagationDelay(i->first);

                int radioStart = i->second->getId();
                int radioEnd = radioStart + i->second->size();
                for (int g = radioStart; g != radioEnd; ++g)
                    sendDirect(static_cast<cPacket*>(msg->dup()),
                               delay, msg->getDuration(), i->second->getOwnerModule(), g);
            }

```
The first section iterates all the outgoing gates (by checking whether the **before last** gate was reached, i.e., `i != --gateList.end();`). For each of these it just sends a message using the for loop with the correct condition (`int g = radioStart; g != radioEnd; ++g)`). However, the next block repeats the same code:
```
            //calculate delay (Propagation) to this receiving nic
			delay = calculatePropagationDelay(i->first);

            int radioStart = i->second->getId();
            int radioEnd = radioStart + i->second->size();
            for (int g = radioStart; g != --radioEnd; ++g)
                sendDirect(static_cast<cPacket*>(msg->dup()),
                           delay, msg->getDuration(), i->second->getOwnerModule(), g);
```
and iterates over something contained within the gate map (I assume this code makes the assumption the last gate has some special properties, without documenting it). However, by using `(int g = radioStart; g != --radioEnd; ++g)`, it essentially only terminates when `i->second->size()` is even (because in each iteration, `radioEnd` is decremented by 1, and `g` is incremented by 1, and the condition checks for equality). If it should go to the before last radio, `g!=radioEnd =1` is indeed correct. The remaining code then continues as the OP mentioned:
```
            sendDirect(msg, delay, msg->getDuration(), i->second->getOwnerModule(), radioEnd);
        }
        else{
            coreEV << "Nic is not connected to any gates!" << endl;
            delete msg;
        }
```
@devilkuro do you have a simulation that actually runs into this code (i.e., `useSendDirect=true` with more than one radio)? It would be great if you could post an example that breaks, so that we can check that the bug is fixed after we change the code!

**Comment by devilkuro** [comment]
I try to create two patch files for testing this issue.

[change radio size to 2 for test.txt](https://github.com/sommer/veins/files/988586/change.radio.size.to.2.for.test.txt)
[fix the endless loop in ChannelAccess.txt](https://github.com/sommer/veins/files/988587/fix.the.endless.loop.in.ChannelAccess.txt)

@namnatulco Yes, this isn't veins-related at all. And it is safe to keep these codes unchanged. I just think they are strange. I also try to track this issue in the mixim. But it has been merged into inet project, and the related codes are totally rewritten.
